<a href="https://colab.research.google.com/github/daniazzam/General/blob/main/ANN_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ANN: 
PART 1: DATA PROCESSING


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
dataset=pd.read_csv('Bank_Customers_Churn_Modeling.csv')
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Lebanon' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


ENCODING CATEGORICAL DATA:
LABEL ENCODING THE "GENDER" COLUMN

In [5]:
from sklearn.preprocessing import LabelEncoder #respondible for the gender part
le = LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Lebanon' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the data into training and testing datasets

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2,random_state=0)

  Feature Scaling to make the data all within same range

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)

PART2: BUILDING THE ANN

Inialaize the ANN

In [12]:
  ann=tf.keras.models.Sequential()

Adding input layer and first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Add another hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Add output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))